name: linkify
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  audioplayers: ^6.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_database: ^11.1.6
  firebase_messaging: ^15.2.6
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_sound: ^9.24.4
  flutter_speed_dial: ^7.0.0
  get_it: ^8.0.2
  go_router: ^14.6.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.1.3
  path: 1.9.1
  permission_handler: ^11.4.0
  record: ^5.2.1
  shared_preferences: ^2.3.1
  sizer: ^3.0.0
  skeletonizer: ^2.0.1
  supabase_flutter: ^2.8.1
  syncfusion_flutter_sliders: ^28.1.38  
  timeago: ^3.7.0
  voice_message_package: ^2.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  syncfusion_flutter_sliders: ^28.1.38

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

# flutter_assets:
#   assets_path:
#     - assets/icons/
#   output_path: lib/core/constants/
#   filename: icons.dart
#   field_prefix:
#   classname: MyIcons
#   ignore_comments: true

# flutter_assets:
#   assets_path:
#     - assets/images/
#   output_path: lib/core/constants/
#   filename: images.dart
#   field_prefix: null
#   classname: MyImages
#   ignore_comments: true

# flutter_assets:
#   assets_path:
#     - assets/animations/
#   output_path: lib/core/constants/
#   filename: animation.dart
#   field_prefix:
#   classname: MyAnimation
#   ignore_comments: true
